version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vacancies_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"


  webapp:
    build:
      context: ./webapp
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  my_parser_data:
